set(Vc_INSTALL_DIR ${EXTERNAL_INSTALL_DIR})
set(Vc_INCLUDE_DIR ${Vc_INSTALL_DIR}/include)
set(Vc_LIBRARY_DIR ${Vc_INSTALL_DIR}/lib)

ExternalProject_Add(Vc_Ext
        GIT_REPOSITORY  "https://github.com/VcDevel/Vc"
        GIT_TAG         "1.4.1"
        UPDATE_DISCONNECTED ${UPDATE_DISCONNECTED}
        SOURCE_DIR      "${EXTERNAL_DIR}/Vc_src"
        BINARY_DIR      "${EXTERNAL_DIR}/Vc_build"
        INSTALL_DIR     "${Vc_INSTALL_DIR}"
        CMAKE_ARGS
        "-DCMAKE_INSTALL_PREFIX=${Vc_INSTALL_DIR}"
        "-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
        "-DCMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}"
        "-DBUILD_TESTING=OFF"
        )

list(APPEND PROJECT_DEPENDENCIES Vc_Ext)
list(APPEND PROJECT_LINK_DIRECTORIES ${Vc_LIBRARY_DIR})
list(APPEND PROJECT_INCLUDE_DIRECTORIES ${Vc_INCLUDE_DIR})